version: '3.5'

services:
  db:
    container_name: db
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - .docker/db/:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres

  testdb:
    container_name: testdb
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - .docker/testdb/:/data/postgres
    ports:
      - '5433:5432'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
