export namespace InterestPointProvider {
  export const INTEREST_POINT_CATEGORY_REPOSITORY = Symbol(
    'INTEREST_POINT_CATEGORY_REPOSITORY',
  );
  export const CREATE_INTEREST_POINT_CATEGORY = Symbol(
    'CREATE_INTEREST_POINT_CATEGORY',
  );
  export const INTEREST_POINT_REPOSITORY = Symbol('INTEREST_POINT_REPOSITORY');
  export const CREATE_INTEREST_POINT = Symbol('CREATE_INTEREST_POINT');
  export const GET_NEARBY_INTEREST_POINTS = Symbol(
    'GET_NEARBY_INTEREST_POINTS',
  );
}
